name: GitHub Contribution Summary
description: Generates a summary of your GitHub contributions as an issue
branding:
  icon: book
  color: blue

inputs:
  token:
    description: GitHub.com token for authentication.
    required: true
    default: ${{ github.token }}
  other_tokens:
    description:
      A comma-separated list of additional GitHub tokens for authentication. For
      example, if you have separate account(s) for GitHub Enterprise Cloud -
      Enterprise Managed User instance(s).
    required: false
  num_days:
    description: The number of days to look back. Defaults to 14.
    required: true
    default: '14'
  openai_model:
    description:
      (Optional) OpenAI API model for generating the summary. This will be added
      as a comment to the issue that is created.
    required: false
    default: gpt-4o-mini
  openai_project:
    description:
      (Optional) OpenAI API project for generating the summary. This will be
      added as a comment to the issue that is created.
    required: false
  openai_token:
    description:
      (Optional) OpenAI API token for generating the summary. This will be added
      as a comment to the issue that is created.
    required: false
  project_number:
    description: (Optional) The project number to create the summary issue in.
    required: false
  repository:
    description:
      'The owner and repository to create the summary issue in. Defaults to the
      repository where this action is invoked. Format: `owner/repo.` If you want
      to create the issue in a different repository than the one where you are
      running this action, ensure the `token` input has sufficient permissions.'
    required: true
    default: ${{ github.repository }}

runs:
  using: node20
  main: dist/index.js
